### PR TITLE
validate plants by place

### PR DESCRIPTION
**Pull request by jeann2013**
**Describe Pull request**
Validate plants by place

### CODE REVIEW

**Comment by tom-osborne** [comment]
@jeann2013 Please can you give more context to this PR. Fill out the template and explain **what** this PR does and **why** you raised it.

Some information on how to test it would also be useful.
Thanks.

**Comment by jeann2013** [comment]
@tom-osborne please check this out https://github.com/qbcore-framework/qb-weed/issues/48

**Comment by OfficialRDB** [comment]
> @tom-osborne please check this out #48

Thanks for the credit btw lol.

`local result = MySQL.prepare.await('SELECT COUNT(*) FROM house_plants WHERE citizenid = ?', {Player.PlayerData.citizenid})`
Where are you getting the `Player.PlayerData.citizenid` data from ? 

`MySQL.insert('INSERT INTO house_plants (building, coords, gender, sort, plantid) VALUES (?, ?, ?, ?, ?)',`
Where are you adding the citizenid into the database ?

Where do you show people how to add a column to the table ? 
I can guarantee this will give people errors, and will let this PR explode.

**Comment by LYRYCAL** [comment]
> > @tom-osborne please check this out #48
> 
> Thanks for the credit btw lol.
> 
> `local result = MySQL.prepare.await('SELECT COUNT(*) FROM house_plants WHERE citizenid = ?', {Player.PlayerData.citizenid})` Where are you getting the `Player.PlayerData.citizenid` data from ?
> 
> `MySQL.insert('INSERT INTO house_plants (building, coords, gender, sort, plantid) VALUES (?, ?, ?, ?, ?)',` Where are you adding the citizenid into the database ?
> 
> Where do you show people how to add a column to the table ? I can guarantee this will give people errors, and will let this PR explode.

Yes, 100% i got error after trying this PR.
Screenshot_1

**Pull request closed without merging**
