### PR TITLE
Fix nil error when table is empty

### PR DESCRIPTION
**Pull request by Borreke0**
**Describe Pull request**
Fixes an error when house table was empty. This throws it away ;)

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by citRaTTV** [comment]
The problem with breaking this while loop is that the script will never detect the `closestPlant`, and therefore won't allow you to interact with a plant if one is planted after entering the house. A better solution would be to return an empty table in the `qb-weed:server:getBuildingPlants` callback on the server side rather than `nil`.

**Comment by citRaTTV** [comment]
> The problem with breaking this while loop is that the script will never detect the `closestPlant`, and therefore won't allow you to interact with a plant if one is planted after entering the house. A better solution would be to return an empty table in the `qb-weed:server:getBuildingPlants` callback on the server side rather than `nil`.

@Borreke0 wanted to check in and see if you've had a chance to check this out

**Comment by Borreke0** [comment]
Hi,

No still need to adjust it but haven’t managed to have the time to do so.
Will check it this weekend !

Verzonden via iPhone


Op do 15 feb 2024 om 18:25 schreef citRa ***@***.***>

**Review by Borreke0 — COMMENTED** [review]
This should be the better solution @citRaTTV 
Can you confirm? ^^

**Comment by citRaTTV** [comment]
> This should be the better solution @citRaTTV 
> Can you confirm? ^^

Looks good @Borreke0 ! You just need to rebase your branch to the latest main and then I'll get this approved for merge

**Pull request closed without merging**
